In [4]:
!pip3 install xlrd
import numpy as np
import pandas as pd

iris = pd.read_excel('iris.xls')
iris

  Using cached https://files.pythonhosted.org/packages/a6/0c/c2a72d51fe56e08a08acc85d13013558a2d793028ae7385448a6ccdfae64/xlrd-2.0.1-py2.py3-none-any.whl


Unnamed: 0         Unnamed: 1        Unnamed: 2         Unnamed: 3  \
0           NaN  Sepal Length (cm)  Sepal Width (cm)  Petal Length (cm)   
1           NaN                  7               3.2                4.7   
2           NaN                6.4               3.2                4.5   
3           NaN                6.9               3.1                4.9   
4           NaN                5.5               2.3                  4   
..          ...                ...               ...                ...   
96          NaN                4.8                 3                1.4   
97          NaN                5.1               3.8                1.6   
98          NaN                4.6               3.2                1.4   
99          NaN                5.3               3.7                1.5   
100         NaN                  5               3.3                1.4   

           Unnamed: 4       Unnamed: 5  Unnamed: 6  Unnamed: 7 Unnamed: 8  \
0    Petal Width (cm)            Class         NaN         NaN      alpha   
1                 1.4  Iris-versicolor         NaN         0.0          0   
2                 1.5  Iris-versicolor         NaN         0.0        NaN   
3                 1.5  Iris-versicolor         NaN         0.0        NaN   
4                 1.3  Iris-versicolor         NaN         0.0        NaN   
..                ...              ...         ...         ...        ...   
96                0.3      Iris-setosa         NaN         NaN        NaN   
97                0.2      Iris-setosa         NaN         NaN        NaN   
98                0.2      Iris-setosa         NaN         NaN        NaN   
99                0.2      Iris-setosa         NaN         NaN        NaN   
100               0.2      Iris-setosa         NaN         NaN        NaN   

    Unnamed: 9  Unnamed: 10  Unnamed: 11  
0          obj          NaN          NaN  
1            0          0.0          1.0  
2          NaN          0.0          1.0  
3          NaN          0.0          1.0  
4          NaN          0.0          1.0  
..         ...          ...          ...  
96         NaN          0.0          1.0  
97         NaN          0.0          1.0  
98         NaN          0.0          1.0  
99         NaN          0.0          1.0  
100        NaN          0.0          1.0  

[101 rows x 12 columns]

In [5]:
iris = iris.dropna(axis='columns')
iris

Unnamed: 1        Unnamed: 2         Unnamed: 3        Unnamed: 4  \
0    Sepal Length (cm)  Sepal Width (cm)  Petal Length (cm)  Petal Width (cm)   
1                    7               3.2                4.7               1.4   
2                  6.4               3.2                4.5               1.5   
3                  6.9               3.1                4.9               1.5   
4                  5.5               2.3                  4               1.3   
..                 ...               ...                ...               ...   
96                 4.8                 3                1.4               0.3   
97                 5.1               3.8                1.6               0.2   
98                 4.6               3.2                1.4               0.2   
99                 5.3               3.7                1.5               0.2   
100                  5               3.3                1.4               0.2   

          Unnamed: 5  
0              Class  
1    Iris-versicolor  
2    Iris-versicolor  
3    Iris-versicolor  
4    Iris-versicolor  
..               ...  
96       Iris-setosa  
97       Iris-setosa  
98       Iris-setosa  
99       Iris-setosa  
100      Iris-setosa  

[101 rows x 5 columns]

In [23]:
iris.iloc[:,0].to_numpy()

array(['Sepal Length (cm)', 7, 6.4, 6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6,
       5.2, 5, 5.9, 6, 6.1, 5.6, 6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3,
       6.1, 6.4, 6.6, 6.8, 6.7, 6, 5.7, 5.5, 5.5, 5.8, 6, 5.4, 6, 6.7,
       6.3, 5.6, 5.5, 5.5, 6.1, 5.8, 5, 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 5.1,
       4.9, 4.7, 4.6, 5, 5.4, 4.6, 5, 4.4, 4.9, 5.4, 4.8, 4.8, 4.3, 5.8,
       5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5, 5, 5.2, 5.2,
       4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5, 5.5, 4.9, 4.4, 5.1, 5, 4.5, 4.4,
       5, 5.1, 4.8, 5.1, 4.6, 5.3, 5], dtype=object)

In [27]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [33]:
sepal = iris.iloc[:,0].to_numpy()
sepal[8]

4.9

In [35]:
sepal[2:4].mean()

6.65

In [36]:
sepal[0:3] = sepal[2:4].mean()
sepal[0:10]

array([6.65, 6.65, 6.65, 6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6], dtype=object)

In [37]:
print(sepal[6])
sepal[6] = sepal[2:4].mean()
print(sepal[6])

5.7
6.775


In [38]:
(sepal[2]+sepal[3])/2

6.775

In [41]:
x = [12,14,np.nan,np.nan,17]

In [42]:
x

[12, 14, nan, nan, 17]

In [43]:
np.isnan(x)

array([False, False,  True,  True, False])

In [47]:
x = [n for n in x if not np.isnan(n)]
x

[12, 14, 17]

In [48]:
y = [12,14,np.nan,np.nan,17]

In [63]:
sum(np.isnan(y))

2

In [50]:
iris_2 = pd.read_excel('iris.xls')
iris_2

Unnamed: 0         Unnamed: 1        Unnamed: 2         Unnamed: 3  \
0           NaN  Sepal Length (cm)  Sepal Width (cm)  Petal Length (cm)   
1           NaN                  7               3.2                4.7   
2           NaN                6.4               3.2                4.5   
3           NaN                6.9               3.1                4.9   
4           NaN                5.5               2.3                  4   
..          ...                ...               ...                ...   
96          NaN                4.8                 3                1.4   
97          NaN                5.1               3.8                1.6   
98          NaN                4.6               3.2                1.4   
99          NaN                5.3               3.7                1.5   
100         NaN                  5               3.3                1.4   

           Unnamed: 4       Unnamed: 5  Unnamed: 6  Unnamed: 7 Unnamed: 8  \
0    Petal Width (cm)            Class         NaN         NaN      alpha   
1                 1.4  Iris-versicolor         NaN         0.0          0   
2                 1.5  Iris-versicolor         NaN         0.0        NaN   
3                 1.5  Iris-versicolor         NaN         0.0        NaN   
4                 1.3  Iris-versicolor         NaN         0.0        NaN   
..                ...              ...         ...         ...        ...   
96                0.3      Iris-setosa         NaN         NaN        NaN   
97                0.2      Iris-setosa         NaN         NaN        NaN   
98                0.2      Iris-setosa         NaN         NaN        NaN   
99                0.2      Iris-setosa         NaN         NaN        NaN   
100               0.2      Iris-setosa         NaN         NaN        NaN   

    Unnamed: 9  Unnamed: 10  Unnamed: 11  
0          obj          NaN          NaN  
1            0          0.0          1.0  
2          NaN          0.0          1.0  
3          NaN          0.0          1.0  
4          NaN          0.0          1.0  
..         ...          ...          ...  
96         NaN          0.0          1.0  
97         NaN          0.0          1.0  
98         NaN          0.0          1.0  
99         NaN          0.0          1.0  
100        NaN          0.0          1.0  

[101 rows x 12 columns]

In [51]:
baris_satu = iris_2.iloc[1,:].to_numpy()
baris_satu

array([nan, 7, 3.2, 4.7, 1.4, 'Iris-versicolor', nan, 0.0, 0, 0, 0.0, 1.0],
      dtype=object)

In [54]:
np.sum(pd.isnull(iris_2.iloc[0,:]))

5

In [55]:
iris_2.iloc[:,1].value_counts()

5                    10
5.1                   9
5.7                   7
5.5                   7
5.4                   6
4.9                   5
4.8                   5
5.6                   5
5.2                   4
5.8                   4
6.1                   4
4.6                   4
6                     4
6.3                   3
4.4                   3
6.7                   3
6.6                   2
5.9                   2
4.7                   2
6.2                   2
6.4                   2
6.9                   1
4.3                   1
6.5                   1
4.5                   1
7                     1
6.8                   1
Sepal Length (cm)     1
5.3                   1
Name: Unnamed: 1, dtype: int64

In [89]:
iris_3 = pd.read_excel('iris.xls')
iris_3

Unnamed: 0         Unnamed: 1        Unnamed: 2         Unnamed: 3  \
0           NaN  Sepal Length (cm)  Sepal Width (cm)  Petal Length (cm)   
1           NaN                NaN               3.2                4.7   
2           NaN                6.4               3.2                4.5   
3           NaN                NaN               3.1                4.9   
4           NaN                5.5               2.3                  4   
..          ...                ...               ...                ...   
96          NaN                4.8                 3                1.4   
97          NaN                5.1               3.8                1.6   
98          NaN                 AV               3.2                1.4   
99          NaN                5.3               3.7                1.5   
100         NaN                  5               3.3                1.4   

           Unnamed: 4       Unnamed: 5  Unnamed: 6  Unnamed: 7 Unnamed: 8  \
0    Petal Width (cm)            Class         NaN         NaN      alpha   
1                 1.4  Iris-versicolor         NaN         0.0          0   
2                 1.5  Iris-versicolor         NaN         0.0        NaN   
3                 1.5  Iris-versicolor         NaN         0.0        NaN   
4                 1.3  Iris-versicolor         NaN         0.0        NaN   
..                ...              ...         ...         ...        ...   
96                0.3      Iris-setosa         NaN         NaN        NaN   
97                0.2      Iris-setosa         NaN         NaN        NaN   
98                0.2      Iris-setosa         NaN         NaN        NaN   
99                0.2      Iris-setosa         NaN         NaN        NaN   
100               0.2      Iris-setosa         NaN         NaN        NaN   

    Unnamed: 9  Unnamed: 10  Unnamed: 11  
0          obj          NaN          NaN  
1            0          0.0          NaN  
2          NaN          0.0          NaN  
3          NaN          0.0          NaN  
4          NaN          0.0          NaN  
..         ...          ...          ...  
96         NaN          0.0          NaN  
97         NaN          0.0          NaN  
98         NaN          0.0          NaN  
99         NaN          0.0          NaN  
100        NaN          0.0          NaN  

[101 rows x 12 columns]

In [90]:
iris_3.iloc[:,1].value_counts()

5                    10
5.1                   8
5.7                   6
S                     6
5.5                   6
6                     4
5.2                   4
4.8                   4
5.4                   4
4.9                   3
4.4                   3
6.3                   3
6.1                   3
5.6                   3
A                     3
6.7                   3
AV                    3
5.8                   3
4.6                   3
6.6                   2
5.3                   1
4.7                   1
5.9                   1
4.3                   1
6.2                   1
4.5                   1
6.4                   1
Sepal Length (cm)     1
6.5                   1
0                     1
6.8                   1
Name: Unnamed: 1, dtype: int64

In [112]:
def total_angka_huruf(x):
    count=0
    count_angka=0
    count_nan=0
    for data in x:
        if isinstance(data,str) == True :
            count+=1
        elif isinstance(data,int) == True or isinstance(data,float) == True:
            if not np.isnan(data):
                count_angka+=1
            else:
                count_nan+=1
    print("jumlah angka : "+str(count_angka)+"\n")
    print("jumlah huruf : "+str(count)+"\n")
    print("jumlah NaN : "+str(count_nan))

In [113]:
total_angka_huruf(iris_3.iloc[:,1])

jumlah angka : 82

jumlah huruf : 13

jumlah NaN : 6


In [95]:
baris_kolom_satu = iris_3.iloc[:,1]

In [98]:
type(baris_kolom_satu[3])

float

In [114]:
len(baris_kolom_satu)

101

In [117]:
baris_baru =baris_kolom_satu.drop(baris_kolom_satu.index[0])

In [118]:
baris_baru

1      NaN
2      6.4
3      NaN
4      5.5
5      6.5
      ... 
96     4.8
97     5.1
98      AV
99     5.3
100      5
Name: Unnamed: 1, Length: 100, dtype: object

In [119]:
total_angka_huruf(baris_baru)

jumlah angka : 82

jumlah huruf : 12

jumlah NaN : 6
